image: golang:latest

before_script:
  - go mod download
  - go mod vendor

stages:
    - test
    - build

test:
    stage: test
    script:
      - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
      - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/alkobot
    artifacts:
      paths:
        - alkobot
