stages:
  - test
  - build
  - push
  - deploy

test:
  image: golang:latest
  before_script:
    - go mod download
    - go mod vendor
  stage: test
  script:
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  image: golang:latest
  before_script:
    - go mod download
    - go mod vendor
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/alkobot
  artifacts:
    paths:
      - alkobot

build:
  image: docker:stable
  stage: build
  script:
    - docker build -t registry.wawan.pro/wawan/alkobot .

push:
  image: docker:stable
  stage: push
  script:
    - docker push registry.wawan.pro/wawan/alkobot
