apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: bots-tls
spec:
  dnsNames:
  - api.wawan.pro
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: bots-tls
